let translate_list = [];

translate_list = [

{name:'Английский', src:'files/en.png', lang:'en'},
{name:'Немецкий', src:'files/de.png', lang:'de'},
{name:'Французский', src:'files/fr.png', lang:'fr'},
{name:'Узбекский', src:'files/uz.png', lang:'uz'},
{name:'Азербайджанский', src:'files/az.png', lang:'az'},
{name:'Албанский', src:'files/sq.png', lang:'sq'},
{name:'Арабский', src:'files/ar.png', lang:'ar'},
{name:'Армянский', src:'files/hy.png', lang:'hy'},
{name:'Белорусский', src:'files/be.png', lang:'be'},
{name:'Болгарский', src:'files/bg.png', lang:'bg'},
{name:'Греческий', src:'files/el.png', lang:'el'},
{name:'Грузинский', src:'files/ka.png', lang:'ka'},
{name:'Датский', src:'files/da.png', lang:'da'},
{name:'Иврит', src:'files/iw.png', lang:'iw'},
{name:'Исландский', src:'files/is.png', lang:'is'},
{name:'Испанский', src:'files/es.png', lang:'es'},
{name:'Итальянский', src:'files/it.png', lang:'it'},
{name:'Казахский', src:'files/kk.png', lang:'kk'},
{name:'Киргизский', src:'files/ky.png', lang:'ky'},
{name:'Корейский', src:'files/ko.png', lang:'ko'},
{name:'Китайский', src:'files/ch.png', lang:'zh-CN'},
{name:'Латышский', src:'files/lv.png', lang:'lv'},
{name:'Литовский', src:'files/lt.png', lang:'lt'},
{name:'Монгольский', src:'files/mn.png', lang:'mn'},
{name:'Норвежский', src:'files/no.png', lang:'no'},
{name:'Персидский', src:'files/fa.png', lang:'fa'},
{name:'Польский', src:'files/pl.png', lang:'pl'},
{name:'Румынский', src:'files/ro.png', lang:'ro'},
{name:'Сербский', src:'files/sr.png', lang:'sr'},
{name:'Словацкий', src:'files/sk.png', lang:'sk'},
{name:'Таджикский', src:'files/tg.png', lang:'tg'},
{name:'Татарский', src:'files/tt.png', lang:'tt'},
{name:'Турецкий', src:'files/tr.png', lang:'tr'},
{name:'Украинский', src:'files/uk.png', lang:'uk'},
{name:'Финский', src:'files/fi.png', lang:'fi'},
{name:'Хорватский', src:'files/hr.png', lang:'hr'},
{name:'Чешский', src:'files/cs.png', lang:'cs'},
{name:'Японский', src:'files/ja.png', lang:'ja'},
]


// Азербайджанский, Албанский, Арабский, Армянский, Белорусский, Болгарский, Греческий, Грузинский, Датский, Иврит, Исландский, Испанский, Итальянский, Казахский, Киргизский, Латышский, Литовский, Монгольский, Норвежский, Персидский, Польский, Румынский, Сербский, Словацкий, Таджикский, Татарский, Турецкий, Туркменский, Украинский, Финский, Хорватский, Чешский,